### ISSUE TITLE
Support "print-scaling" option

### ISSUE THREAD

**Issue by michaelrsweet** [OpenPrinting/cups-filters#108]
The "print-scaling" option is the standard IPP Everywhere option for controlling the scaling of the output; currently defined values are:

- `auto`: if the “ipp-attribute-fidelity” attribute is true or the document is larger than the requested media, scale the document using the 'fit' method if the margins are non- zero, otherwise scale using the 'fill' method. If the “ipp-attribute-fidelity” attribute is false or unspecified and the document is smaller than the requested media, scale using the 'none' method.
- `auto-fit`: if the “ipp-attribute-fidelity” attribute is true or the document is larger than the requested media, scale the document using the ‘fit’ method. Otherwise, scale using the ‘none’ method.
- `fill`: scale the document to fill the requested media size, preserving the aspect ratio of the document data but potentially cropping portions of the document.
- `fit`: scale the document to fit the printable area of the requested media size, preserving the aspect ratio of the document data without cropping the document.
- `none`: do not scale the document to fit the requested media size. If the document is larger than the requested media, center and clip the resulting output. If the document is smaller than the requested media, center the resulting output.

This attribute is defined in [PWG 5100.16: IPP Transaction-Based Printing Extensions](https://ftp.pwg.org/pub/pwg/candidates/cs-ipptrans10-20131108-5100.16.pdf).

**Comment by tillkamppeter** [comment]
@dheeraj135, could you add this functionality? The actual implementation you have already done with issue #65, issue #63, and pull request #92. What you need to add now is that this functionality is also triggered appropriately by the print-scaling attribute as Mike has shown in the initial posting.
- `print-scaling=fill`: This is your "fill-page" asked for in the original posting of issue #65, a photo is cropped to the aspect ratio of the output page so that it fills the page exactly.
- `print-scaling=fit`: This is the "fitplot" or "fit-to-page" which we had before. The photo is scaled to the fill the imageable area of the destination page the best possible without cropping anything.
- `print-scaling=none`: This is the "crop-to-fit" which you had added to solve issue #63, only centering the input page and cropping what is too large to fit the output page, the best way to print A4 input on a Letter output page or vice-versa keeping the size of the graphical elements on the page.

Please also implement the two auto settings which are simply a selection of one of the three others depending on the “ipp-attribute-fidelity” attribute and the size of the input page compared to the size of the output page.
The implementation should be done in the filters `imagetoraster`, `imagetopdf`, and `pdftopdf`.
Thanks in advance.

**Comment by dheeraj135** [comment]
@tillkamppeter Sure, I will work on it.

**Comment by dheeraj135** [comment]
@tillkamppeter @michaelrsweet, I am not sure how I should compare the size of the document and the media. Suppose the dimension of an image is [100,150] and, that of media is [120,90]. What should be the expected behaviour of ```auto-fit``` option?

**Comment by tillkamppeter** [comment]
@dheeraj135, first the input page is considered larger than the output frame, as the height of 150 does not fit into the height of 90. Even if we allow rotating to fit the output page the input page is still larger than the output page.
What happens when the "auto-fit" setting is used depends on the state of the “ipp-attribute-fidelity” IPP attribute. If it is set, we have to apply the "fit" method (aka "fit-to-page" or "fitplot"), with “ipp-attribute-fidelity” not set we have to apply the "none" method (the "crop-to-fit" which you had added to fix issue #63).

**Comment by aluminaceramix** [comment]
CUPS 2.4.6 in FreeBSD.
print photo image, can't keep aspect ratio in -o print-scaling=fit.
then fit to paper size in vertical and horizontal each scaled.
I want to print shrink image to fit paper size in keep aspect ratio.

**Comment by hhartzer** [comment]
> CUPS 2.4.6 in FreeBSD. print photo image, can't keep aspect ratio in -o print-scaling=fit. then fit to paper size in vertical and horizontal each scaled. I want to print shrink image to fit paper size in keep aspect ratio.

I'm having this issue as well with 2.4.7. Even with `-o print-scaling=crop-to-fit`.

**Comment by aluminaceramix** [comment]
Thank you for reply.

I'm sorry to stupid, I want to shrink image and get white space to print whole image and fit paper size in keep aspect ratio.

**Comment by hhartzer** [comment]
I'd like to do the same thing. I'm trying to pring a jpeg and it won't scale properly with `-fit-to-page`.

**Comment by aluminaceramix** [comment]
grep -R crop-to-fit in cups-2.4.7 source code, not found.
I test print by -o fit-to-page, then vertical and horizontal each scaled, not keep image aspect ratio.
I want whole image printing with *keep* image aspect ratio.

**Comment by tillkamppeter** [comment]
@aluminaceramix note that these options are not implemented in CUPS itself but in cups-filters. For cups-filters 1.x in the "1.x" branch of the cups-filters repository (this repository) and for cups-filters 2.x in the libcupsfilters repository.
