### ISSUE TITLE
Configure script does not abort, when certain Poppler headers are missing

### ISSUE THREAD

**Issue by paulmenzel** [OpenPrinting/cups-filters#114]
The configure script should error out, if certain Poppler headers cannot be found.

    checking for POPPLER... yes
    checking poppler/cpp/poppler-version.h usability... no
    checking poppler/cpp/poppler-version.h presence... no
    checking for poppler/cpp/poppler-version.h... no

In Debian Sid/unstable with `libpoppler-dev` 0.71.0-3 and without `libpoppler-cpp-dev` installed, the error below happens.

    filter/pdftoraster.cxx:2149:11: error: 'memCheck' is not a member of 'Object'
       Object::memCheck(stderr);
               ^~~~~~~~
    filter/pdftoraster.cxx:2150:3: error: 'gMemReport' was not declared in this scope
       gMemReport(stderr);
       ^~~~~~~~~~

**Comment by tanmayanand44** [comment]
@paulmenzel As a temporary fix, you must build poppler from source and enable the xpdf-headers using ``./configure --enable-xpdf-headers`` to configure poppler. These error is due to our pdftoraster using non-public api's of poppler that are derived from xpdf. We are currently working to change the pdftoraster to use only the public api's of poppler and you will see the patch soon. For more information head over [here](https://github.com/OpenPrinting/cups-filters/issues/9)

**Comment by tillkamppeter** [comment]
Closing as this problem will be solved with issue #9.
