### ISSUE TITLE
net printer doesn't print any more

### ISSUE THREAD

**Issue by paolobenve** [OpenPrinting/cups-filters#120]
Hi! I have 4 ubuntu bionic pc's on my intranet, with a multifunction sharp printer, an MX-2310U, which always printed perfectly until a few days ago.

Since some day ago I cannot print any more from any PC, while it seems that from a Windows PC printing is ok (the printer technician who came for assistance told me so).

Apparently, on the PC side the printing job ends well, and the job is sent to the printer. Actually, the printer leaves the stand-by, makes some noise but does not print anything.

/var/log/cups/error_log show many lines, but I don't understand if there is any error:

https://pastebin.com/tD8UnfKE

Is this a bug?

**Comment by tillkamppeter** [comment]
I do not see anything wrong in your error_log, neither on job processing nor on communication with the printer.
So please first, gfet your printer's PPD file from /etc/cups/ppd/ and attach it here. Rename it to have the extension `.txt` added to the original name so that GitHub accepts it.
The run the following command to isolate the filtering:
```
cupsfilter -p [PPD] -m application/vnd.cups-postscript [INPUT] > out.ps.txt 2> log.txt
```
This does the conversion of your input file (PDF, plain text, or other printable formats) into the PostScript which your printer needs, with the default option settings embedded. Replace `[PPD]` by the PPD file which you have extracted in the first step and `[INPUT]` by your input file.
Please attach the files `log.txt` and `out.ps.txt` to this bug report.
Have a look into `log.txt` whether there are any errors and into `out.ps.txt` whether it is actually a PostScript file. Run
```
gs out.ps.txt
```
to see whether it gets correctly displayed on the screen by Ghostscript.
You can send the `out.ps.txt` file directly to the printer without further filtering:
```
lp -oraw out.ps.txt
```
Does your printer print it?

**Comment by paolobenve** [comment]
I resolved when something explained me that that printer doesn't accept ps input, it needs pcl

**Comment by sherwinkh** [comment]
@tillkamppeter 
I encounter the same issue.
I use web browser to add my Label Printer，and shared it on Ubuntu Mate 16.04.2.
Then add printer device use “http://192.168.1.79:631/printers/Deli_DL-888B” on Win7.
I printe a test label，the printer makes some noise but does not print anything.
```
root@rk3288:/usr/local/cups# lpinfo -v
network lpd
network ipps
network ipp
network socket
network https
network http
root@rk3288:/usr/local/cups# lpinfo -v
network ipps
network http
network lpd
network ipp
network socket
direct usb://Deli/DL-888B(NEW)
network https
root@rk3288:/usr/local/cups# cupsfilter -p Deli_DL-888B.txt -m application/vnd.cups-postscrip test.txt > out.ps.txt 2> log.txt
root@rk3288:/usr/local/cups# cat log.txt 
cupsfilter: Unknown destination MIME type application/vnd.cups-postscrip.
```

**Comment by tillkamppeter** [comment]
@sherwinkh, it looks like that you do not have all filters installed. There must be filters `texttopdf`, `pdftopdf`, and `pdftops` filters in your `/usr/lib/cups/filter` directory. Do you have cups-filters installed? Note that after installing missing filters you have to restart CUPS.

**Comment by sherwinkh** [comment]
@tillkamppeter After installing the cups-filters ,`gs out.ps.txt` can get correctly displayed on the screen by Ghostscript.But `lp -oraw out.ps.txt` get nothing,ant the status of the printer is "Sending data to printer." all the time.
```
root@rk3288:/usr/local/cups# lp -d DL888B -oraw out.ps.txt 
request id is DL888B-7 (1 file(s))
root@rk3288:/usr/local/cups# lpstat -p
printer DL888B now printing DL888B-7.  enabled since Fri 23 Aug 2019 04:00:54 AM UTC
	Sending data to printer.
root@rk3288:/usr/local/cups#
```
