### ISSUE TITLE
DefaultOutputOrder not working

### ISSUE THREAD

**Issue by fernandopioli** [OpenPrinting/cups-filters#140]
I installed a zebra GC420t to print labels, each label has default side.
I need to set the print side of the labels.
I tried:
*DefaultOutputOrder: Reverse
in .ppd, but didn't work.
(if I change darkness in ppd, it works fine)

I'm printing by mono in raspibian.
I need help please

**Comment by tillkamppeter** [comment]
Which version of cups-filters are you using? Please try the current version as there were done some fixes on the output order recently.
If the problem still occurs with the newest version, please attach the PPD file (add `.txt` to the end of the file name so that GitHub acceps the upload) and also provide a [CUPS error_log in debug mode](https://wiki.ubuntu.com/DebuggingPrintingProblems#CUPS_error_log) of a print job.

**Comment by fernandopioli** [comment]
I am using v 2.2. But I got it with a work around. I set up the printer in Ubuntu, so in Ubuntu there is an option in the GUI that allows you to change the paper order. Then I copied Ubuntu's .ppd to raspibian and it worked. It wasn't the best way, but it worked

**Comment by tillkamppeter** [comment]
This is probably a problem in the Zebra printer driver which is part of CUPS. You should report a bug at [CUPS](https://github.com/apple/cups).
