### ISSUE TITLE
cups-browsed: Print queue for pwg-raster local printer is not created.

### ISSUE THREAD

**Issue by dheeraj135** [OpenPrinting/cups-filters#141]
If we have a local printer(ippeveprinter/ippserver) which supports only **image/pwg-raster** and **application/octet-stream**, then cups-browsed(default cups-browsed.conf file) is not able to create a print queue for this printer.

If we set ```CreateIPPPrinterQueues All``` then the print queue is created.
But if we use ```CreateIPPPrinterQueues Everywhere``` or ```CreateIPPPrinterQueues Driverless``` then the print queue is not created.

Attribute file of the printer: [pwg.attr.txt](https://github.com/OpenPrinting/cups-filters/files/3512414/pwg.attr.txt)

**Comment by dheeraj135** [comment]
To create ipp printer supporting only **image/pwg-raster** and **application/octet-stream**, simply use the attribute file as: ```ippserver -a pwg.attr.txt pwg_test_printer```.
Alternatively, build ippsample for this source: https://github.com/dheeraj135/ippsample. Then use the ippeveprinter utility as: ```./ippeveprinter pwg_test_printer```

**Comment by tillkamppeter** [comment]
I have found out what the problem is.
An IPP printer which supports PWG Raster do not only have to tell this in its "document-format-supported" attribute but also provide the "pwg-raster-document-resolution-supported" to tell a client which resolutions (in dpi) the PWG Raster files need to have so that the printer is able to print them. A typical laser printer would list 300 dpi and 600 dpi here.

**Comment by tillkamppeter** [comment]
So the bug is in the printer emulator(s) of ippsample (and also CUPS). If a certain PDL is supported also the keywords for the parameters of the PDL need to be present. This is valid for Apple Raster, PWG Raster, and PCLm.
Please report bugs on the appropriate upstream projects and also take this into account in the Printer Application framework, especially for the raster-only mode,

**Comment by tillkamppeter** [comment]
The attributes AFAIR are:
Apple Raster:
- `urf-supported`

PWG Raster:
- `pwg-raster-document-type-supported`
- `pwg-raster-document-resolution-supported`
- `pwg-raster-document-sheet-back`

PCLm:
- `pclm-source-resolution-supported`
- `pclm-source-resolution-default`
- `pclm-strip-height-supported`
- `pclm-strip-height-preferred`
- `pclm-raster-back-side`
- `pclm-compression-method-preferred`

**Comment by dheeraj135** [comment]
@tillkamppeter 
From the attributes file, we have the following attributes:
ATTR resolution **pwg-raster-document-resolution-supported** 300x300dpi,600x600dpi
ATTR keyword **pwg-raster-document-type-supported** "black_1","sgray_8"
ATTR mimeMediaType document-format-supported "application/octet-stream","**image/pwg-raster**"

**pwg-raster-document-sheet-back** is missing but this attribute is *CONDITIONALLY REQUIRED*. Reference: [Pwg raster format](https://ftp.pwg.org/pub/pwg/candidates/cs-ippraster10-20120420-5102.4.pdf). Page 37.

So, I don't think this bug is in the emulator.

**Comment by tillkamppeter** [comment]
I have found what went wrong, the "pwg-raster-document-resolution-supported" was checked as a keyword type but is of resolution type. I have fixed this in commit 01726b3bbf5d01 now.
Thanks for the bug report.
