### ISSUE TITLE
[question] pdftopdf preserves encryption?

### ISSUE THREAD

**Issue by zdohnal** [OpenPrinting/cups-filters#146]
Hi,
I was looking into pdftopdf filter code, seeing how it works and find out that pdftopdf filter produces encrypted files if input file is encrypted.
Is it based on a specification of filtering? Or is it just for convenience? Would it be possible that I create the patch which disables the encryption in pdftopdf filter and could be added into project?

**Comment by tillkamppeter** [comment]
The pdftopdf filter does not use any PDF interpreter, it does only manipulations on the PDF file, as re-ordering pages, removing, multiplying pages, scaling, rotating, ... No page is rendered or converted to another file format or internal structure (for example vector text/graphics to raster image). Probably due to thsi encrypted elements are not decrypted but passed on encryoted.
Up to now no one complained about that, so it seems that pdftopdf did its work correctly this way.
Could you tell what the problem caused by the current behavior of pdftopdf is?
Patches are welcome. Simply post a pull request.

**Comment by zdohnal** [comment]
Our crypto people is trying to get rid of weaker hashes/ciphers and they are not happy when pdftopdf filter 'creates' (in matter of speaking, because it is only data which are sent to next filter and no new file is not created) new weakly encrypted (with usage of MD5 and RC4) file based on old weak encrypted file. According to them it would be better to just decrypt the file.

**Comment by tillkamppeter** [comment]
Thank you very much, I have merged it now.

**Comment by zdohnal** [comment]
Thank you merging it, Till!
