### ISSUE TITLE
Brother DCP-357C broken with latest updates

### ISSUE THREAD

**Issue by sobrus** [OpenPrinting/cups-filters#156]
Hi,

My distro (Manjaro) had CUPS updated recently to version 2.3. Unfortunately this breaks my printer, Brother DCP-357C. 
Any CUPS version higher than 2.2.11 refuses to work (both 2.2.12 and 2.3). The error is "Filter failed" and "Invalid PPD file" Error in line 219.

The printer was working fine on Linux since 2011, on various linux distributions.

Downgrading cups, cups-filters and libcups packages solves the problem.

**Comment by tillkamppeter** [comment]
This is most probably due to the fact that your PPS file contains an option with a choice names "Custom", which is very common in PPD files and also does not break Adobe's PPD specs, but CUPS 2.2.12 and newer does not accept this any more. This is not a bug in cups-filters but in CUPS, please report the bug there.
