### ISSUE TITLE
PS Level 1 forced for grayscale PDF rendering with Poppler/Cairo

### ISSUE THREAD

**Issue by efuss** [OpenPrinting/cups-filters#169]
Commit 13ff13d, supposed to fix Issue #96, forces the PostScript Level to 1 (`pdf_argv[1] = (char *)"-level1";`) when rendering PDFs with Poppler or Cairo for grayscale output.
I couldn't find any rationale for this in the discussion or commit message.
For us, when printing scanned images, this causes a more than fifteen-fold increase in data size and a threefold increase in printer's processing time.

What problem is this trying to fix?

**Comment by tillkamppeter** [comment]
The reason why PostScript level 1 is used here is that the Poppler utilities `pdftops` and `pdftocairo` have no explicit functionality to convert the incoming PDF into monochrome/grayscale PostScript. So the contributor of said commit used as a workaround PostScript level 1. See `man pdftops` and there `-level1` and `-optimizecolorspace`. As for now I recommend you to use Ghostscript instead of Poppler (see documentation of `pdftops` in the README file). Perhaps a MuPDF-based path would work, too.
As QPDF used in the `pdftopdf` filter also does not support conversion to grayscale it seems that the conversion needs to be explicitly done by some filter or this functionality is restricted to Ghostscript (and perhaps MuPDF) due to lack of functionality in Poppler..

**Comment by efuss** [comment]
> the contributor of said commit used as a workaround PostScript level 1.
Ah, I see. But this appears to be a rather large sledgehammer for the special case of (as far as I understand) wanting to print a colour file as grayscale on a colour printer. Especially if it encumbers the case of printing a grayscale file on a b/w printer.

I'll look into this in more detail after my vacation.

> As for now I recommend you to use Ghostscript instead of Poppler
I forgot the details, but we evaluated all the different PDF-to-PS renderers; each one caused different pain and Poppler caused the smallest overall pain for our use-case.

**Comment by magicalmarisa** [comment]
This commit also breaks `pdftocairo` since in this case `-ps,` which is a mandatory option, gets replaced by `-level1.` Furthermore `pdftocairo` doesn't even understand the options `-level1` or `-optimizecolorspace`. 

> D [04/Nov/2019:11:45:17 +0100] [Job 366858] Running command line for pdftocairo: pdftocairo -level1 -level3 -origpagesizes -nocenter -r 600 -optimizecolorspace /var/spool/cups/tmp/035ab5dcc009c -
> D [04/Nov/2019:11:45:17 +0100] [Job 366858] Started filter pdftocairo (PID 23402)
> D [04/Nov/2019:11:45:17 +0100] [Job 366858] Started filter pstops (PID 24119)
> D [04/Nov/2019:11:45:17 +0100] [Job 366858] pdftocairo version 0.76.1
> D [04/Nov/2019:11:45:17 +0100] [Job 366858] Copyright 2005-2019 The Poppler Developers - http://poppler.freedesktop.org
> D [04/Nov/2019:11:45:17 +0100] [Job 366858] Copyright 1996-2011 Glyph & Cog, LLC
> D [04/Nov/2019:11:45:17 +0100] [Job 366858] Usage: pdftocairo [options] <PDF-file> [<output-file>]
> [...]
> D [04/Nov/2019:11:45:17 +0100] [Job 366858] The print file is empty.
> D [04/Nov/2019:11:45:17 +0100] [Job 366858] PID 23402 (pdftocairo) stopped with status 99!
> D [04/Nov/2019:11:45:17 +0100] [Job 366858] PID 24119 (pstops) stopped with status 1!

**Comment by tillkamppeter** [comment]
I improved the MuPDF path ("`pdftops-renderer=mupdf`") recently. You should try it (again).
Generally, Ghostscript and MuPDF both support color space conversions, like color input to grayscale output without rasterization (if input and output formats are both vector formats, like PDF or PostScript). Poppler does not have this capability. In addition, the QPDF used by `pdftopdf` does not do color space conversions at all, probably because QPDF is only a PDF manipulator and not a PDF renderer/interpreter.
This means that if you want to use Poppler as PDF renderer for the PostScript conversion and nowhere else Ghostscript or MuPDF should be used, there is no way in cups-filters to convert an input PDF which is in color into an output PostScript file which is grayscale, at least if you do not rasterize the PDF or make use of awkward side effects ("`pdftops -level1 ...`").
Allowing rasterization in the special case of needing a grayscale PDF `pdftops` could call `pdftoraster` followed by `rastertops` as `pdftoraster` converts the (always colored) Poppler output into grayscale .

**Comment by tillkamppeter** [comment]
Removed the PostScript Level 1 hack for grayscale output with Poppler, as it generates huge output files with `pdftops` and does not work at all with `pdftocairo` (commit 0818ee322).
Now if printing a grayscale job on a PostScript printer no conversion will happen if Poppler is used as PDF renderer, leading to color output on color PostScript printers, at least as no printer-internal grayscale conversion is triggered by commands embedded into the PostScript output stream.
There are warning issued in the CUPS error_log, hinting that Ghostscript or MuPDF should be used as PDF renderer.
