### ISSUE TITLE
Unsupported PDF data for Direct Print :1000 when printing a PDF

### ISSUE THREAD

**Issue by vb1494** [OpenPrinting/cups-filters#170]
While printing a PDF (CUPS printing in Linux server using command lpr -P <filename>) i get a paper printed with the following data : "Unsupported PDF data for Direct Print :1000". When tried in Windows, it got printed without any issues. Could anyone please help in finding a solution for this?

**Comment by tillkamppeter** [comment]
Can you attach the PDF file here? Could you also attach the PPD file of the print queue (in `/etc/cups/ppd/`, you need to rename it to have the extenstion `.txt` added so that GitHub accepts it)?
Could you follow the instructions in the section "CUPS error_log" [here](https://wiki.ubuntu.com/DebuggingPrintingProblems) and attach the resulting error_log file (also add `.txt` to the file name, log must contain the logging of at least one job)?

**Comment by tillkamppeter** [comment]
Could you also tell us which printer (manufacturer and model) you are using?

**Comment by tillkamppeter** [comment]
No answer for several months. Closing ...
