### ISSUE TITLE
Remote printing: HWMargins applied twice

### ISSUE THREAD

**Issue by smurfix** [OpenPrinting/cups-filters#185]
My setup is as follows: I'm printing using a Brother QL-570 label printer with the ptouch raster driver. That driver generates PPD files with a hardware margin of 1.5mm, which is nonsense because the printer can print to the edge. So I fixed that. The resutt works but measuring I found that the old margin was in fact 3mm when I used the printer remotely from another system. Thus I conclude that the hardware margin was applied twice. Owch.

The print command used was `lpr -PLabeller -o CutMedia=LabelEnd -o AdvanceDistance=0 -o page-left=0 -o page-right=0 -o page-top=0 -o page-bottom=1 -o PageSize=Custom.38x21mm -o fit-to-page random_image.pnm`. I did not yet test with other file formats, glabel, or whatever.

Any ideas how to narrow down and/or fix this would be appreciated.

**Comment by tillkamppeter** [comment]
On both server and client please set CUPS into debug logging mode via
```
cupsctl --debug-logging
```
Print a job (with the original PPD with margins) from the client. After that take the `/var/log/cups/error_log` files of both server and client and attach them here. Note that you have to rename them to have a `.txt` extension so that you can attach them to this issue.

**Comment by tillkamppeter** [comment]
No answer for more than a month. Closing.
