### ISSUE TITLE
More than 10 s delay printing to IPP printer

### ISSUE THREAD

**Issue by paulmenzel** [OpenPrinting/cups-filters#203]
Using Debian Sid/unstable with cups-filters 1.27.0-2, printing to the *Epson WorkForce WF-2660* over IPP, it takes several seconds until the job starts. Please find the network capture with Wireshark attached when printing a blank page from LibreOffice [attached]](https://github.com/OpenPrinting/cups-filters/files/4214195/cups-ipp.pcapng.gz).

**Comment by tillkamppeter** [comment]
Could you attach the PPD file of the queue (from `/etc/cups/ppd/` directory) and also a CUPS error_log (in debug mode, to activate with `cupsctl --debug-logging`) with one job?

**Comment by paulmenzel** [comment]
Here you go: [error_log.txt](https://github.com/OpenPrinting/cups-filters/files/4241447/error_log.txt)

**Comment by tillkamppeter** [comment]
@paulmenzel, could you please add your printer's PPD file from `/etc/cups/ppd/`. Thanks.

**Comment by paulmenzel** [comment]
Here you go: [EPSON_WF_2660_Series.ppd.txt](https://github.com/OpenPrinting/cups-filters/files/4394834/EPSON_WF_2660_Series.ppd.txt)

**Comment by tillkamppeter** [comment]
@paulmenzel, thanks. Could you set debugging in cups-browsed, editing `/etc/cups/cups-browsed.conf` to have a line
```
DebugLogging file
```
and restart cups-browsed.
Now print your job again and observe. If you still get the delay, attach the file `/var/log/cups/cups-browsed_log` and `/var/log/cups/error_log`. Rename them adding a `.txt` extension so that GitHub accepts them.
If your print job comes out without delay, try another job, until you get a delay. Then attach the log files to this bug report. Please also tell the number of the job which actually had the delay, so that we do not need to weed through problem-free jobs.
Thanks in advance.

**Comment by tillkamppeter** [comment]
Could you try cups-filters 1.28.6? It has several improvements in cups-browsed.

**Comment by paulmenzel** [comment]
Sorry for not updating the issue. I think it was fixed by the newer version. I haven’t heard a report from the users mentioning the issue in a long time.
