### ISSUE TITLE
cups-filters-1.27.2 - foomatic-rip produces no output

### ISSUE THREAD

**Issue by zdohnal** [OpenPrinting/cups-filters#215]
Hi Till,

the issue with foomatic-rip reappeared in 1.27.2 - it seems one commit from last Thursday broke the printing via foomatic-rip again - I'll try to look up which one.

PPD: 
[test1.ppd.txt](https://github.com/OpenPrinting/cups-filters/files/4286287/test1.ppd.txt)
PS file:
[prolog.ps.txt](https://github.com/OpenPrinting/cups-filters/files/4286290/prolog.ps.txt)
Job log:
[log.txt](https://github.com/OpenPrinting/cups-filters/files/4286302/log.txt)

**Comment by tillkamppeter** [comment]
What is exactly wrong here? the file `prolog.ps.txt` does not contain any page. When I open it with Ghostscript I do not get a single "showpage" prompt. The `log.txt` which I assume is of you printing this file to a queue using `test1.ppd.txt` as its PPD file, shows that foomatic-rip discovered that the input file has no pages, giving an appropriate debug message. foomatic-rip passes on zero bytes for nothing to be printed and no error issued on the print queue. This looks all correct for me.

**Comment by zdohnal** [comment]
It makes sense - I and the reporter of the bug [here](https://bugzilla.redhat.com/show_bug.cgi?id=1809763) got confused because those postscript files were printed out in earlier versions. But when I convert pdf to ps and try to print created ps file - printing works.
I'm sorry for the noise.

**Comment by albert-fluegel** [comment]
I am the reporter of the bug [there](https://bugzilla.redhat.com/show_bug.cgi?id=1809763) and i don't understand what Mr. zdohnal is talking about. As i report there, the [uploaded file](https://bugzilla.redhat.com/attachment.cgi?id=1667298) (align.ps is created, when downloaded) from the foo2zjs distribution is not printed anymore with cups-filters-libs-1.27.1. Mr. zdohnal states, that this is normal, because this file is allegedly no valid postscript. I don't see, what this has to do with the files i find here in his first comment. align.ps is valid postscript and should be printed. Probably it does not contain all possible comments for the postscript document structuring conventions, but this is irrelevant for being printed either by a real postscript capable printer or by any converter like gs with appropriate options. Indeed for this prolog.ps.txt , that really contains only definitions, no printed page is produced. However this is not my reported case.

**Comment by tillkamppeter** [comment]
[align.ps.txt](https://github.com/OpenPrinting/cups-filters/files/4321163/align.ps.txt)
[bunti.ppd.txt](https://github.com/OpenPrinting/cups-filters/files/4321206/bunti.ppd.txt)

`align.ps` is not made for printing, it is for executing it with Ghostscript, so that Ghostscript calculates margin adjustment. It does not make sense to convert it to PDF, what in the CUPS printing workflow happens first, and it also does not make sense to send it to a printer, not even raw.

So not being able to print this file with CUPS is not actually a bug.

Here you can see some examples on how the file behaves:

The file `align.ps` (attached) is treated correctly by foomatic-rip alone. You can test with the line:
```
cupsfilter -p bunti.ppd -i application/vnd.cups-postscript -m printer/xxx -o PageSize=A4 -e align.ps > out
```
Note that the file `align.ps` should be used with this filename, not `align.ps.txt` as the attachment. So rename this file before trying the command line.
The file is a very unusual PostScript file (normal PostScript files print correctly):
```
gs align.ps
```
displays the file correctly and
```
gs -q -dPARANOIDSAFER -dNOPAUSE -dBATCH -sDEVICE=bbox align.ps 2>&1 | grep -c HiResBoundingBox
```
counts the pages of the file correctly, being 1. Only it takes an unusually long time to complete.
Renaming the file makes Ghostscript error on displaying or on counting pages:
```
gs align.ps.txt
gs -q -dPARANOIDSAFER -dNOPAUSE -dBATCH -sDEVICE=bbox align.ps.txt 2>&1 | grep -c HiResBoundingBox
```
Also injecting it through stdin does not work:
```
cat align.ps | gs -
```

**Comment by zdohnal** [comment]
@albert-fluegel I'm sorry I chose the incorrect word in our bug description - your ps file is valid, but it is not printable as @tillkamppeter explains in its comment.
