### ISSUE TITLE
Broken cross-compilation without dejavu font

### ISSUE THREAD

**Issue by ffontaine** [OpenPrinting/cups-filters#262]
Cross-compilation is broken since commit 1d66106e5ae45407b01459cb112ee09752166dba. Indeed, when cross-compiling, the dejavu font won't be installed in /usr/share/fonts. The path (e.g. `$(TARGET_DIR)/usr/share/fonts/dejavu/DejaVuSans.ttf`) could be provided through `--with-test-font-path`  which will fix the build failure but this will result in broken test programs. As dejavu font is only needed for tests, it could be useful to revert this change or add a --disable-test option

**Comment by tillkamppeter** [comment]
My suggestion is that there should be a `--with-test-font` command line option to adapt the font path and the possibility to alternatively supply `--without-test-font` which makes all tests needing this font being skipped.

**Comment by zdohnal** [comment]
Hi @ffontaine ,

reverting the commit at configure.ac would bring up the original issue - tests will fail because the font cannot be found.

Would you mind helping me with reproducing the issue? I ran:

```
$ ./configure --build i686-pc-linux-gnu --host i586-mingw32msvc
```

IIUC [gnu.org page](https://www.gnu.org/software/automake/manual/html_node/Cross_002dCompilation.html), it should configure the compiling tools for cross compilation - and I don't get any error during configure process.

Just a side-note:
The commit you are referring to was changed some time ago via #240 . I use the current master for testing.

@tillkamppeter if the issue persists with the current master, what about only adding ${TARGET_DIR} into AS_IF check, but save the proper path into TESTFONT? It will check a place, where the font is during cross-compiling, but the compiled test will use the real path.
It seems easier to implement and without other configure option, but I base my solution on TARGET_DIR being defined during configure.

**Comment by ffontaine** [comment]
The build failure are raised by the buildroot autobuilders since we bumped to version 1.27.5: http://autobuild.buildroot.org/?reason=cups-filters-1.27.5 so it includes #240.

This issue is raised when the build machine does not have any `/usr/share/fonts/ ` directory:
```
find: `/usr/share/fonts': No such file or directory
configure: error: DejaVuSans.ttf font file is missing. Please install a package providing it.
```
or when `DejaVuSans.ttf` can't be found in `/usr/share/fonts/`:
`configure: error: DejaVuSans.ttf font file is missing. Please install a package providing it.`

On buildroot side, we're not really interested in building or running tests as we're targetting embedded devices so an option to disable this check would be nice, I tried to set `--with-test-font-path` to `/dev/null` but this does not work as `/dev/null` is not a standard file. An other option would to hardcode TESTFONT to "/usr/share/fonts/dejavu/DejaVuSans.ttf" if cross_compiling is set. Would it be acceptable? If this is the case, I can send a PR.

**Comment by tillkamppeter** [comment]
I think my `--with-test-font`/`--without-test-font` should work for you. You could either skip the tests using `--without-test-font` or set any fixed font path with `--with-test-font`.

**Comment by zdohnal** [comment]
@ffontaine I'm sorry I'm not familiar with cross compiling. The pull request looks good to me.

**Comment by zdohnal** [comment]
So $cross_compiling is the variable which is needed, thanks for the info!
