### ISSUE TITLE
Installing cups-filter mess up my system

### ISSUE THREAD

**Issue by dausruddin** [OpenPrinting/cups-filters#269]
Hi. I was trying to install this, until I got this issue after running `sudo checkinstall`
> ![](https://i.imgur.com/atk5wDx.jpg)
All commands produce error "No such file or directory" . Even opening a new tab in my firefox with crash the tab.
I rebooted and it just stuck at boot.

I cannot find a solution so eventually I reinstalled my system and lost all except important files that I backed up.

I couldn't believe cups-filter did that. So I try again after the fresh install. Turned out this is the culprit. I am no expert, and now I am reinstalling my system again, so the picture is the only think I could give.

Maybe because of checkinstall?

Can someone help me? I want to install this on my Ubuntu 20.04.

Thanks!

**Comment by tillkamppeter** [comment]
I have never used `checkinstall` and up to now no one complained about installation of cups-filters with this utility.
`checkinstall` builds a `.deb` package from the files installed by `make install`, then installs the resulting package. This approach should usually work if you try to install a software which is not already provided by the system or installed on the system via `.deb` packages. For example if you want to have the newest libreoffice and use this facility, you would need to remove the libreoffice installation of your operating system first, and only then run `checkinstall`. I do not know what happens if you install something which overwrites files which come from already installed packages.
So first, did you remove ALL packages of cups-filters from your system? Note that cups-filters is installed as many individual packages, like libcupsfilters, cups-browsed, ... Note also that because of dependencies of other packages you probably cannot simply remove all of cups-filters.
As I do not know how `checkinstall` proceeds when installing the package it generated, whether it removes packages which provided the files previously, forces breakage of dependencies, forces overwriting of other package's files, ... you should do a non-impact test before. For this run
```
sudo checkinstall --install=no
```
instead of simply `sudo checkinstall`. This only generates the package. After that, list the content of the generated package:
```
dpkg -c [name].deb > file-list.txt
```
Please attach the resulting `file-list.txt` to this bug report.
Check the list whether important system files are contained which should not get overwritten.

**Comment by dausruddin** [comment]
I have uninstalled every cups-related packages by manually removing them that appeared in `dpkg -l | grep cups` except for libcups2 which **libgtk-3-0** is depending on.

I am setting up a VM environment which I'm going to use to test it. I'll proceed with your suggestion and will report back.

Thanks for the reply!

**Comment by dausruddin** [comment]
Nope. `sudo checkinstall --install=no` still breaking the system
> ![Screenshot from 2020-07-28 00-12-31](https://user-images.githubusercontent.com/5763466/88565414-25a4fd00-d067-11ea-92da-ff360312608a.png)

I only have this before installing cups and cups-filter
> ![Screenshot from 2020-07-28 00-14-26](https://user-images.githubusercontent.com/5763466/88565561-5edd6d00-d067-11ea-87ab-d8a8e913d004.png)

So I decided to use `make install` instead. Had to delete `/usr/lib/cups/filter/foomatic-rip` to make the installation successful tho.

`checkinstall` is pretty old. I should stop using it. I really appreciate your reply. Now my printer is working great :)

Thanks a lot!
