### ISSUE TITLE
Printer configured, but not visible

### ISSUE THREAD

**Issue by jochenw** [OpenPrinting/cups-filters#349]
Hi,

I've got a Laptop running Fedora 33, with cups-filters 1.28.7:

        [jwi@tarqeq ~]$ rpm -qi cups-filters | grep Source
        Source RPM  : cups-filters-1.28.7-2.fc33.src.rpm

The Cups server is uptodate with regards to the configuration. I did ensure that by running

       sudo systemctl restart cups

I have a default printer configured in my [printers.conf](https://github.com/OpenPrinting/cups-filters/files/6114739/printers.conf.txt)

So, I'd expect "lpstat -p" to show my printer. Which it doesn't:

        [jwi@tarqeq ~]$ lpstat -p
        lpstat: No destinations added.

If I visit the Cups administration instead ( http://192.168.9.4:631/printers/?QUERY= ), then I get the message "No printers"  (More precisely, I get the german equivalent: "Keine Drucker")

Error log [here](https://github.com/OpenPrinting/cups-filters/files/6114743/cups_log.txt).

 Edited by zdohnal.

**Comment by zdohnal** [comment]
Reported in [Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1937101).

**Comment by zdohnal** [comment]
@jochenw 

Actually the default printer looks fishy - it says it is driverless, but uses ```socket``` backend, and additionally it is a fax queue, not a print queue - at least that's what I understand from:

```
Brother MFC-L3750CDW series, Fax, driverless, cups-filters 1.28.5
```
How did you install this queue?

IMO the strange setup above could influence CUPS to don't show the queue - we can see what ```cupsd``` says about the queue when you restart cups service - because that's the time when ```cupsd``` loads permanents queues from ```printers.conf```.

So would you mind following the steps [here](https://fedoraproject.org/wiki/How_to_debug_printing_problems#CUPS_generic_issue) and get the logs from ```cupsd``` during restarting the service (so your trigger is ```$ sudo systemctl restart cups```)?

P.S. please don't paste the logs as you did in the first comment - the ticket is difficult to read when log longer than 10 lines is pasted in. Github or any other ticket portal like bugzilla supports adding attachments. Github is capable of attaching any files with .txt suffix, so you can just add the suffix to your text file and click on 'selecting' word in the comment box.

**Comment by Bhavna2020** [comment]
hi
Could you please confirm whether the driverless command is working on your system or not.

**Comment by Bhavna2020** [comment]
And please state the results here.

**Comment by BhavnaKosta** [comment]
The problem might be occurring because:

1. CUPS server is only listening to localhost and not able to read printers. To fix this, configure the /etc/cups/cupsd.conf file to listen on an external IP address, i.e, change
Listen localhost : 631
to
Listen <dns name server> : 631
and then restart cups and cups-browsed.

OR 

2. Configure the ~/.cups/client.conf file, as the work network defined in it has made the lpstat -s freeze and the system is not able to read the printers.

**Comment by Bhavna2020** [comment]
The problem might be occurring because:

1. CUPS server is only listening to localhost and not able to read printers. To fix this, configure the /etc/cups/cupsd.conf file to listen on an external IP address, i.e, change
Listen localhost : 631
to
Listen <dns name server> : 631
and then restart cups and cups-browsed.

OR 

2. Configure the ~/.cups/client.conf file, as the work network defined in it has made the lpstat -s freeze and the system is not able to read the printers.

**Comment by jochenw** [comment]
I did the following:

- Completely removed all Cups packages. (While doing so, I noticed that some of them have been installed twice, which might explain all kinds of strange behaviour.)
- Reinstalled the same packages, resulting in a basically empty /etc/cups/printers.conf.
- Opened the "printers" dialog in the GNOME control center. Noticed, that there is a printer, most likely detected automatically.
- Used this printer successfully for printing.

Closing this issue, thank you all very much!
