### ISSUE TITLE
Add a simple "fill page" scaling option to imagetoraster and pdftopdf (print-scaling=fill)

### ISSUE THREAD

**Issue by speachy** [OpenPrinting/cups-filters#65]
Imagetoraster, by default, scales the input image to fill the output page, while respecting the image's aspect ratio.

Unless the input and output aspect ratios are a near-perfect match, this often results in uneven borders/margins, or on full-bleed printers, unsightly white lines on one or more edges, and there is no simple way to avoid this without a-priori knowledge of the printer's native capabilities and using that in a pre-printing "filter" crop the image to the correct aspect ratio.

What I'd like to see is another scaling option that will scale the image's shorter dimension to match the printer's shorter dimension, then crop the excess off the longer dimension.  By default we would center the image in the page, but the "position" option could be used to change that.

This is the same idea behind Gutenprint's 'StpiShrinkOutput=Crop' option, but that feature is useless in a CUPS printing flow because imagetoraster generates a raster that already fits the aspect ratio.

On the surface this seems like it would be fairly straightforward to implement (given what imagetoraster already can accomplish), so if I bang this out, is it (in principle) something that would be accepted into cups-filters?

**Comment by tillkamppeter** [comment]
Thank you very much in advance for your suggested code contribution.
It would be great to have this functionality in cups-filters and I appreciate very much if you could provide the code changes as a pull request.
Could you please consider the following:
- Every job is going through either `pdftopdf` or `imagetopdf`, more through `pdftopdf` even as applications usually send jobs in PDF format. So the functionality should be added to both `pdftopdf` and `imagetopdf` filters. Especially note that photo apps send photos usually as PDF.
- The option which activates the normal scaling of the input pages to the output page size is the boolean option `fit-to-page`. We would need a new option, perhaps named `crop-to-page` or `fit-to-page-crop` (suggestions?) for this. If there is an IPP attribute for this operation it should also be understood by the filters.
- The option should not be activated by default, as for non-photo documents it does the wrong thing in the most cases (cutting off text for example). For photos it is probably the most convenient way to print.

**Comment by speachy** [comment]
Yes, I still intend to work on this, but I haven't progressed beyond a small pile of comments in the existing source code.

(Life has got in the way of my ability to hack on printer stuff..)

**Comment by tillkamppeter** [comment]
For the correct option see the print-scaling IPP attribute, in section 6.2.2 of [this document](https://ftp.pwg.org/pub/pwg/candidates/cs-ipptrans10-20131108-5100.16.pdf). "fit" is to blow up the document content as much as possible without loosing any content, as the "fitplot" or "fit-to-page" do. This is the best for getting text documents filling the page. "fill" is what you are looking after, it blows up the content to fully cover the page, cutting off some of the content at two sides of the page. This is best for photos, so that they completely fill up the sheet. If you did not frame your picture too tightly when shooting it, you get it automatically full-bleed printed.
What you have to do is to implement this option in both `pdftopdf` and `imagetoraster`.

**Comment by dheeraj135** [comment]
@tillkamppeter Is there any other filter which already implements this functionality?

**Comment by tillkamppeter** [comment]
No, AFAIK not.
Another interesting additional mode would be crop-to-fit, meaning that the incoming image/PDF is conserved in size and centered, for cases where size conservation is important and/or the original file has a weird, slightly off-standard size making the printer asking for inserting that size's paper. See this bug report:
https://bugs.launchpad.net/bugs/1813432

**Comment by dheeraj135** [comment]
@tillkamppeter 
I don't think we need to change ``` imagetoraster ``` filter because as you earlier mentioned that every print job is going either through ``` imagetopdf ``` or ``` pdftopdf ```. Is ``` imagetoraster ``` in the title intentional or is it a typo? 
I fired a print job and it used ``` imagetopdf ```, **not** ``` imagetoraster ```.
Logs:
```
I [14/Feb/2019:01:35:10 +0530] [Job 12] Started filter /home/dh/cupsi/lib/cups/filter/imagetopdf (PID 7692)
I [14/Feb/2019:01:35:10 +0530] [Job 12] Started filter /home/dh/cupsi/lib/cups/filter/pdftops (PID 7693)
I [14/Feb/2019:01:35:10 +0530] [Job 12] Started backend /home/dh/cupsi/lib/cups/backend/cups-pdf (PID 7694)
```

**Comment by tillkamppeter** [comment]
Seems that you have found a bug, as if the workflow goes through PDF always `pdftopdf` should be executed.

**Comment by tillkamppeter** [comment]
Or does `imagetopdf` do all tasks of `pdftopdf` so that we could allow to go without? This needs to be checked.

**Comment by dheeraj135** [comment]
@tillkamppeter I am printing a jpg file. So, I think ``` imagetopdf ``` is justified.

**Comment by tillkamppeter** [comment]
For `imagetoraster` try a printer which uses a CUPS-Raster based driver (or a driverless printer using a raster input format, like PWG Raster, Apple Raster, or PCLm, NOT PDF) and print an image to it.

**Comment by tillkamppeter** [comment]
Independent of the fact whether `pdftopdf` actually gets used or not, we can only consider this feature request completed if both image files and PDF files as input (or simply ANY input file) support the new settings, especially because if you print from a photo editor/manager the app sends the photo as PDF file.

**Comment by speachy** [comment]
imagetoraster is useful for printers that don't consume PDF natively.  It's more efficient to convert image->raster->native than image->pdf->raster->native.

As for my ability to work on this issue, thanks to a change in my family employment situation I have much less time than expected to work on side projects.  So if someone else is interested in working on this, by all means, please do so.

**Comment by speachy** [comment]
> Independent of the fact whether `pdftopdf` actually gets used or not, we can only consider this feature request completed if both image files and PDF files as input (or simply ANY input file) support the new settings, especially because if you print from a photo editor/manager the app sends the photo as PDF file.

IMO if this is only implemented in the 'pdftopdf' filter, then we should remove the imagetoraster filter, so that all images unconditionally go through imagetopdf..

**Comment by dheeraj135** [comment]
@tillkamppeter I created one test printer with ippserver : ``` ippserver -f image/pwg-raster t1 ```
These are the filters used: 
```
D [14/Feb/2019:02:45:50 +0530] [Job 16] 4 filters for job:
D [14/Feb/2019:02:45:50 +0530] [Job 16] imagetopdf (image/jpeg to application/vnd.cups-pdf, cost 65)
D [14/Feb/2019:02:45:50 +0530] [Job 16] gstoraster (application/vnd.cups-pdf to image/pwg-raster, cost 99)
D [14/Feb/2019:02:45:50 +0530] [Job 16] - (image/pwg-raster to printer/t1/image/pwg-raster, cost 100)
D [14/Feb/2019:02:45:50 +0530] [Job 16] - (printer/t1/image/pwg-raster to printer/t1, cost 0)
```

**Comment by dheeraj135** [comment]
Ok, for printers with cups-raster format, it uses ``` imagetoraster ``` filter.
Printer created with: ``` ippserver -v -f application/vnd.cups-raster t2 ```
Logs:
```
D [14/Feb/2019:03:07:50 +0530] [Job 17] 3 filters for job:
D [14/Feb/2019:03:07:50 +0530] [Job 17] imagetoraster (image/jpeg to application/vnd.cups-raster, cost 100)
D [14/Feb/2019:03:07:50 +0530] [Job 17] - (application/vnd.cups-raster to printer/t2/image/pwg-raster, cost 0)
D [14/Feb/2019:03:07:50 +0530] [Job 17] - (printer/t2/image/pwg-raster to printer/t2, cost 0)
```

**Comment by tillkamppeter** [comment]
There are rules suggesting the use of `imagetoraster` in the `mime/cupsfilters.convs` file, but probably their cost value is too high to make the path using this filter selected by CUPS. But perhaps one can force this path by lowering the cost value or removing the executable bit of `imagetopdf` (restart cupsd when doing changes like this).
We do not have to necessarily implement all features in all the filters of `pdftopdf`, `imagetopdf`, and `imagetoraster`. Also implementing everything in `pdftopdf`, removing `imagetoraster`, and letting `imagetopdf` being always used together with `pdftopdf` (for example by modifying all the `imagetopdf` rules to have `application/pdf` and not `application/vnd.cups-pdf` as output format) could be a solution.

**Comment by tillkamppeter** [comment]
Another thought: Minimizing the number of filters needed for a job can make the processing faster, as less processes, pipes, and temporary files are involved.

**Comment by dheeraj135** [comment]
I made required changes in ``` imagetopdf ``` filter for a single orientation. These are the results:
Input file: 
![jpg](https://user-images.githubusercontent.com/28601604/52777686-61622780-306a-11e9-93e5-090a6b5e0d56.jpg)

Output file: [jpg.jpg___cups-pdf_dh-job_25.pdf](https://github.com/OpenPrinting/cups-filters/files/2864286/jpg.jpg___cups-pdf_dh-job_25.pdf)
@tillkamppeter Can you please confirm if this is the required output? What is the best way to check code with all available options(margins, orientation etc.)?

**Comment by tillkamppeter** [comment]
For a given target format you need input files
- In portrait and landscape orientation, and also square
- "Longer" aspect ratios (for example 16:9 on a 3:2 target format)
- "Shorter" aspect ratios (for example 4:3 on a 3:2 target format)
- The same aspect ratio as the target
These are 7 input files for a given target format.
Test also a square target format.
Test also with PDF input files on the `pdftopdf` filter.
Test also with and without unprintable borders.

**Comment by tillkamppeter** [comment]
The sample image looks OK for me. This is how I imagined how it should work.

**Comment by dheeraj135** [comment]
> No, AFAIK not.
> Another interesting additional mode would be crop-to-fit, meaning that the incoming image/PDF is conserved in size and centered, for cases where size conservation is important and/or the original file has a weird, slightly off-standard size making the printer asking for inserting that size's paper. See this bug report:
> https://bugs.launchpad.net/bugs/1813432

Please correct me if I am wrong. In both ```scaling=fill``` and ```crop-to-fit``` mode, we will crop the input file according to the page's aspect ratio and center it(or use the position to get the desired location). Difference between crop-to-fit and scaling=fill is that in scaling=fill we will stretch the input file to match the page's size.
@tillkamppeter

**Comment by tillkamppeter** [comment]
We need the following modes:

1. Preserve the paper size of each page: This was always the default when not using the `scaling` option. If you print a document which for example contains mainly A4 and some A3 pages and the printer has both A4 and A3 loaded (or A3 is inserted into the manual feed when the printer asks for it), it pulls the correct paper for each page, same for letter with envelope if the correct papers are loaded.
2. fit-to-page (fitplot): Each incoming page is scaled to the selected page size (PPD default setting or setting of PageSize/media-size/media option if supplied) in a way that the full incoming page is fitting into the printable area of the output page size, to guarantee not loosing any of the page content. If aspect ratio of input page and output imageable area do not match, the re will be wider empty borders on 2 edges.
3. fill: The mode for which this thread was started. The incoming page is scaled so that it completely fills the imageable area of the whole output page (the whole output page if we have selected a borderless/fullbleed paper size). If aspect ratio of input page and output imageable area do not match, the input page is cropped appropriately. This mode is mainly for photos to print them borderless on all 4 edges on a photo printer.
4. crop-to-fit: This is the extra one which I brought in. He we do not scale at all. We preserve the scale of the input page. If the output page size is different to the input page size we center the input page and crop off which goes out of the imageable area of the output page. If the input page size is smaller than the output page size we get wider empty borders all around.

The last three also allow printing any document on a printer with only a single page size loaded (and no manual loading on printer's demand).
If not potherwise stated by the user the input page always gets centered on the output page.

**Comment by tillkamppeter** [comment]
Please also test the suitability of the `crop-to-fit` setting with Issue #63.

**Comment by dheeraj135** [comment]
@tillkamppeter 
Let's say we have a page of dimension: W: 576.000000 H: 756.000000
and an image of dimension: W: 2592 H: 3872.
What should be the output of crop-to-fit?

**Comment by tillkamppeter** [comment]
Assuming that the units of these numbers are the same (for example PostScript points, 1.72 inch) the input page is huge and so only a small portion of the center of the input page will show as output page.
Note that there are always option settings which are unsuitable in certain situations. crop-to-fit is mainly for situations where the user wants to print A4 input documents on Letter paper or vice-versa or where input pages have a size which slightly differs from the standard size and so causes annoying prompts for inserting the correct paper size by the printer.
crop-to-fit requires also that the input image has somehow a "real size" like 10x15 cm, or A4, or 576x756 PostScript points. If it has only a size of  2592x3872 pixels , the crop-to-fit does not make sense. So if the input is PDF (`pdftopdf` filter) the option makes sense, but in the `imageto...` filters you need to check whether the input has some defined size (perhaps via some default size/resolution?).
Also make sure that no option gets applied twice (OK if never two of `pdftopdf`, `imagetopdf`,  `imagetoraster` get used).

**Comment by dheeraj135** [comment]
@tillkamppeter I converted a letter-sized pdf to image. But the converted image was larger than letter size. I got same results with A4-sized pdf.
I think, in case of images, crop-to-fit doesn't make any sense. For images, it is best to use either fitplot or fillprint.

**Comment by tillkamppeter** [comment]
Yes, there can always be options which do not make sense in certain situations. If you have an image which has no size in any absolute units then `crop-to-fit` is not applicable and should be ignored.
