### ISSUE TITLE
bannertopdf should not depend on Poppler

### ISSUE THREAD

**Issue by tillkamppeter** [OpenPrinting/cups-filters#8]
bannertopdf generates PDF files for banner pages and test pages. It does not render existing PDF files, so it does not need a PDF interpreter, so Poppler is not really needed for this task. QPDF would be good enough here. QPDF is a helper to generate and modify PDFs, especially to create a correct XREF table.
Also we want to give the user the liberty to use cups-filters with one single PDF interpreter, one of Ghostscript, Poppler, and MuPDF, so that on devices with low resources (mobile, IoT, ...) one does not need the redundancy of more than one PDF interpreter.
Currently one looses banner and test page functionality if one does not have Poppler installed, so actually only Poppler works as a single PDF interpreter for cups-filters.
It is also possible that bannertopdf uses non-public (internal) APIs of Poppler which can make it easily break with updates of Poppler, but I am not sure whether this is really the case.
Therefore we need to convert bannertopdf to use QPDF instead of Poppler.
Hint: All Poppler use is in filter/pdf.cxx.

**Comment by sahilarora535** [comment]
@tillkamppeter 
1. I have found the banner file format specifications from here: [CUPS Banner File Format](https://www.cups.org/doc/spec-banner.html)
As per the specifications sheet, the mime type for banner file is supposed to be `application/vnd.cups-banner`. However, in cups-filter, the mime type is `application/vnd.cups-pdf-banner`. Are they the same format?
https://github.com/OpenPrinting/cups-filters/blob/bfedcf27c7c69aa337521abdfffe5811bd5d479c/mime/cupsfilters.types#L103

2. In the specifications sheet mentioned above, there is no mention of the keyword `Template`, `Font` or `Font-size` in a banner file. However, in sample banner files which can be found [here](https://github.com/OpenPrinting/cups-filters/tree/master/banners), there are these keywords used. Is there a separate specifications sheet for this file format where one can see all permissible keywords? Though I have found these keywords in code which is responsible for parsing them here:

https://github.com/OpenPrinting/cups-filters/blob/bfedcf27c7c69aa337521abdfffe5811bd5d479c/filter/banner.c#L163-L187

I guess these are all the permissible banner keywords.

3. In the code which deals with parsing these keywords, it can be seen that `bannertopdf` does not support conversion of `Image` and `Notice` keywords.

https://github.com/OpenPrinting/cups-filters/blob/bfedcf27c7c69aa337521abdfffe5811bd5d479c/filter/banner.c#L179-L183

Do these keywords have to be supported when we convert the filter to use QPDF instead of Poppler? Is it possible?

**Comment by tillkamppeter** [comment]
The banner file format does not match the original CUPS format. As we are working with PDF now, we have improved the flexibility by dropping the support for inserting images but instead, allowing a template PDF file. This PDF file is scaled into the page and contains graphical elements which a certain banner ot test page always should have, like the big "CLASSIFIED" or the logo of the company, in case of the test page some color patches.
This means that some keywords of the old CUPS format got dropped and other keywords added. You should not use banner or test page files of old CUPS versions, but the ones which come with cups-filters.
Your QPDF incarnation of bannertopdf needs to be compatible with the bannertopdf which currently comes with cups-filters, meaning to use the same keywords. Ideally you only modify pdf.cxx and none ofnthe other files, actually in the other files you only remove which is specific to Poppler and perhaps replace it by appropriate QPDF counterparts.
The full list of keywords to actually support I assume is https://github.com/OpenPrinting/cups-filters/blob/bfedcf27c7c69aa337521abdfffe5811bd5d479c/filter/banner.c#L163-L178 But do not modify the keyword interpreter. Simply replace all Poppler-based code by equivalent code based on QPDF, probably you only need to actaually change code in pdf.cxx and change some definitions and includes in pdf.h.

**Comment by sahilarora535** [comment]
@tillkamppeter 
> Simply replace all Poppler-based code by equivalent code based on QPDF, probably you only need to actaually change code in pdf.cxx and change some definitions and includes in pdf.h.

The file [filter/foomatic-rip/foomaticrip.c](https://github.com/OpenPrinting/cups-filters/blob/master/filter/foomatic-rip/foomaticrip.c) also uses the file we are planning to change, i.e. [pdf.h](https://github.com/OpenPrinting/cups-filters/blob/master/filter/pdf.h) and [pdf.cxx](https://github.com/OpenPrinting/cups-filters/blob/master/filter/pdf.cxx). What does this `foomaticrip` filter do? And will it by any chance cause some issues if poppler is replaced by QPDF in the above mentioned files?

**Comment by tillkamppeter** [comment]
foomaticrip.c das an `#include "pdf.h"` but this included foomatic-rip's own `pdf.h` in the same directory which is the header of foomatic-rip's own `pdf.c`. This has nothing to do with the `pdf.h` and `pdf.cxx` in the `filter/` directory. You see this also when doing `ldd /usr/bin/foomatic-rip` on the command line. The output does not list `libpoppler`.

**Comment by tillkamppeter** [comment]
This should also solve issue #14 and issue #15.

**Comment by smilingthax** [comment]
Note that pdf.cxx's `pdf_fill_form()` uses some functionality not (yet?) easily doable with QPDF (also cf. https://github.com/qpdf/qpdf/issues/72 ...)

BTW, https://github.com/OpenPrinting/cups-filters/blob/master/filter/bannertopdf.c#L183 does not do any escaping for pdf strings. It probably isn't to difficult to let bannertopdf create invalid pdf with certain parameters ...

**Comment by sahilarora535** [comment]
@tillkamppeter Is this the same issue of PDF form flattening which has been mentioned by @smilingthax 
Issue: https://github.com/qpdf/qpdf/issues/72

Also, @smilingthax, what kind of problems can we expect while converting Poppler to QPDF, and how should we overcome that? It would be great if you could tell us bit more on this.

**Comment by tillkamppeter** [comment]
@sahilarora535, I do not know how bannertopdf exactly works. A student made it as GSoC project many years ago and it simply worked, So I accepted it as part of cups-filters. Most probably it does not use the PDF feature of fillable forms.

**Comment by smilingthax** [comment]
No, it's not really the same problem. bannertopdf inserts text strings atop an existing template pdf (e.g. `data/default.pdf`), but it also has a special feature to fill "recognized" form fields in the template (e.g. `data/form_english.pdf`), when the field-name(?) matches one of the option-names(?).

To do this, it `pdf_fill_form()` uses poppler methods to access the existing form-fields, modifies them, and (manually) regenerates their appearance stream. But QPDF does not have any method to specifically deal with forms. So every call to those poppler function has to be implemented ourselves...

Now a/the solution to https://github.com/qpdf/qpdf/issues/72 will require methods that specifically deal with form fields, esp:
  1) iterate form fields, and
  2) regenerate appearance streams.

Thus, we should avoid implementing two different solutions to what could be handled with a single, slightly more comprehensive, set of form-handling functions (which might become part of QPDF).
E.g.: as pdftopdf will always be called after bannertopdf (IIRC), it won't have to regenerate the appearance stream immediately, but just rely on pdftopdf's flattening.

Other than that, I don't think there are any big obstacles in converting bannertopdf to use QPDF instead of poppler. It does use the `fontembed`-library which I implemented for texttopdf; this part could probably be simplified and moved to a separate file (fontembed basically requires some pdf-library specific output methods; texttopdf uses simple string-based pdf generation from `pdfutils.c / .h`, for which I've added the `emb_pdf_simple_*`-methods to `fontembed/embed_pdf.c / .h`. `pdf.cxx` contains output methods for poppler. When using QPDF, one(I?) could either simply try to `QPDFObjectHandle::parse()` the strings from `emb_pdf_simple_*`, or implement a qpdf-specific wrapper). I'm not sure, though, whether using a multi-byte font embedding for fonts used in a form field is a good idea. As the whole fontconfig-support in bannerpdf doesn't even seem to work yet, 

Regarding the missing escaping: pdfutils.c provides pdfOut_putString that can be used, when pdfutils is used as pdf-output; qpdf AFAIK does the escaping when using QPDFObjectHandle::unparse(); and popper certainly has its own way...
Either bannertopdf adds its own pdf-output-library independent escaping implementation, or it commits itself to a certain output library, or a method to abstract away the underlying pdf-library could be added to pdf.h (problem: pdf libraries seem to have quite different approaches to handle content streams).

**Comment by sahilarora535** [comment]
@tillkamppeter : It seems it does use the PDF fillable forms feature as @smilingthax  mentioned.

@smilingthax  : So the not working of `font-embed` with `bannertopdf` could be a reason why `Font` keyword does not work with PDF files. I tried adding this to a banner file:
```
Font Ubuntu
```
Apart from that, I tried changing the values to `Arial`, `Roboto`, etc., still I did not find any font change in the resulting PDF. Also, the change is font size when used the keyword `Font-size` is only when the font has been embedded in a form. If otherwise it is tried to change the font properties using the keyword `Show`, things remain the same. Is it the expected behaviour of `bannertopdf`?

For instance, for the underlying banner file:
```
#PDF
#PDF-BANNER
Template default.pdf
Show job-id
Font-size 33
Font Ubuntu
```
No changes were seen when I changed the `Font-size` and `Font` keywords.

Also,
> But QPDF does not have any method to specifically deal with forms. So every call to those poppler function has to be implemented ourselves...

This means we'll have to add features to QPDF to enable form filling.

For this,
> Regarding the missing escaping: pdfutils.c provides pdfOut_putString that can be used, when pdfutils is used as pdf-output; qpdf AFAIK does the escaping when using QPDFObjectHandle::unparse(); and popper certainly has its own way...
Either bannertopdf adds its own pdf-output-library independent escaping implementation, or it commits itself to a certain output library, or a method to abstract away the underlying pdf-library could be added to pdf.h (problem: pdf libraries seem to have quite different approaches to handle content streams).

I did not quite get what you meant by `missing escaping` since I am very new to `bannertopdf`. It would be very helpful if you could explain a bit more about what is escaping and why it is required.

Thank you.

**Comment by smilingthax** [comment]
Regarding escaping, see the PDF Reference (e.g. for version 1.7, Section 3.2.3 String Objects):

> Within a literal string, the backslash (\) is used as an escape character for various purposes, such as to include newline characters, nonprinting ASCII characters, unbalanced parentheses, or the backslash character itself in the string.

Line 183 in bannertopdf.c (link in my first comment) does not do this.

The most recent version on bannertopdf on my machine (cups-filters 1.18.0-3) produces Syntax Errors when viewed with xpdf, caused by https://github.com/OpenPrinting/cups-filters/blob/master/filter/pdf.cxx#L224 creating String-Objects instead of Name-Objects (compare with the pre-poppler 0.58 version, right below it). 

Other than that, e.g.

    PRINTER="ab)c" /usr/lib/cups/filter/bannertopdf 1 "" "" 1 "" /usr/share/cups/banners/standard > out.pdf

will produce an invalid pdfm because it contains unbalanced unescaped paren in a string object:

    [...]
    (Printer: ab)c) Tj T*
    (Printed at: unknown) Tj T*
    [...]

**Comment by smilingthax** [comment]
Regarding the font stuff, I'm not sure what `banner-font`, etc. is supposed to do. The current implementation only applies it to the form (tries to), and seems to have problems even doing that. As a form font is AFAIR already specified/contained in the template pdf (when it contains a valid pdf form), I don't see much value in bannertopdf overriding it afterwards, while probably adding some non-trivial problems (multibyte vs. single byte encoding in forms, anyone?).

Regarding adding form-filling to qpdf ... well, that'd be nice ... for now, just the things needed for form-flattening in pdftopdf are still work-in-progress ... but, if that's something you want to work on, I'll happily support you ...

**Comment by sahilarora535** [comment]
I understood escaping, thanks a lot.
Allow me to make some progress in `bannertopdf`, and I will surely get back if I need some help.

Thanks a lot again.

**Comment by tillkamppeter** [comment]
Probably you can do the whole adaptation to QPDF in pdf.cxx. If not, it is no problem to convert bannertopdf.c into C++. And for that you do not need to restructure the whole bannertopdf.c, as C is a subset of C++ it would be enough to rename bannertopdf.c into bannertopdf.cxx and then do the needed QPDF calls in it.
But first see whether it is possible to do the whole switchover only in pdf.cxx.

**Comment by davygravy** [comment]
@tillkamppeter , @sahilarora535 : 

1.   Is it now the case that cups-filters no longer depends on poppler/libpoppler at all?

2.   this dependency is completely changed to qpdf, without any loss in function?

Thank you in advance,

Dave

**Comment by tillkamppeter** [comment]
@davygravy:
1. cups-filters still contains filters which use Poppler, `pdftoraster` and `pdftops` to support Poppler as one of the three available PDF interpreters (the two others are Ghostscript and MuPDF), but you can build cups-filters without Poppler as you can as well work with one of the other PDF interpreters. They are all equally supported.
Note that QPDF is NOT a PDF interpreter. So you cannot render/rasterize PDF with QPDF and so you cannot generally replace Poppler by QPDF. QPDF is only a PDF manipulator, especially useful for generating valid PDF files, like in `bannertopdf`or `rastertopdf`/`rastertopclm`.
2. Yes, in `bannertopdf` the dependency is completely moved to QPDF without any loss of functionality.
